version: "3"
services:
  redis:
    image: redis
    restart: always
    command: redis-server --save 20 1 
    ports:
      - "6379:6379"
    volumes:
      - place_cache:/data
  placeapi:
    image: placeapi
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "81:80"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
      - cassandra
    volumes:
      - ./api/app:/code/app
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - place_cache:/data
    depends_on:
      - redis
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
volumes:
  place_cache:
  cassandra_data:
